config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :expense_reports, only: [:new, :create, :show] do
    resources :expenses, only: [:new, :create, :show]
    resources :comments, only: [:new, :create, :show]
    post 'submit'
    post 'approve'
  end
  resources :expense_types, only: [:new, :create, :show]
  resources :expense_subtypes, only: [:new, :create, :show]
  resources :customers, only: [:index, :new, :create, :show] do
    post 'approve'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :expense_report
  belongs_to :user
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, :social_name, :cnpj, presence: true
  has_many :expenses
  belongs_to :user
  enum status: { pending: 0, active: 1, inactive: 2 }
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :value, presence: true
  belongs_to :expense_report
  belongs_to :expense_subtype
  belongs_to :customer, optional: true
end

app/models/expense_report.rb
class ExpenseReport < ApplicationRecord
  validates :title, :start_date, :end_date, presence: true
  belongs_to :user
  has_many :expenses
  has_many :comments
  enum status: { saved: 0, submitted: 1, approved: 2, rejected: 3, finished: 4 }
end

app/models/expense_subtype.rb
class ExpenseSubtype < ApplicationRecord
  belongs_to :expense_type
  has_many :expenses
  validates :description, :accounting_account, presence: true
end

app/models/expense_type.rb
class ExpenseType < ApplicationRecord
  has_many :expense_subtypes
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :expense_reports
  has_many :customers
  has_many :comments
  enum profile: { salesman: 0, approver: 2, admin: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    @expense_report =  ExpenseReport.find(params[:expense_report_id])
    @comment.expense_report_id = @expense_report.id
    @comment.user = current_user

    if @comment.save
      redirect_to @expense_report
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @pending_customers = Customer.where(status: :pending)
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    @customer.user = current_user

    if @customer.save
      redirect_to @customer
    else
      flash[:error] = 'Não foi possível cadastrar este cliente'
      render :new
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def approve
    @customer = Customer.find(params[:customer_id])
    @customer.active!
    redirect_to @customer
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :social_name, :cnpj, :status)
  end
end

app/controllers/expense_reports_controller.rb
class ExpenseReportsController < ApplicationController
  def show
    @expense_report = ExpenseReport.find(params[:id])
    @comment = Comment.new
  end

  def new
    @expense_report = ExpenseReport.new
  end

  def create
    report_params = params.require(:expense_report).permit(:title, :start_date,
                                  :end_date, :own_car)

    @expense_report = ExpenseReport.create(report_params)
    @expense_report.user = current_user

    if @expense_report.save
      redirect_to expense_report_path(@expense_report)
    else
      flash[:error] = 'Não foi possível criar este relatório.'
      render :new
    end
  end

  def submit
    @expense_report = ExpenseReport.find(params[:expense_report_id])
    @expense_report.submitted!
    redirect_to @expense_report
  end
end

app/controllers/expense_subtypes_controller.rb
class ExpenseSubtypesController < ApplicationController
  def new
    @expense_subtype = ExpenseSubtype.new
    @expense_types = ExpenseType.all
  end

  def create
    @expense_types = ExpenseType.all

    expense_subtype_params = params.require(:expense_subtype).permit(
                                                :description, :accounting_account,
                                                :expense_type_id, :needs_customer)

    @expense_subtype = ExpenseSubtype.create(expense_subtype_params)

    if @expense_subtype.save
      redirect_to @expense_subtype
    else
      flash[:error] = 'Não foi possível cadastrar.'
      render :new
    end
  end

  def show
    @expense_subtype = ExpenseSubtype.find(params[:id])
  end
end

app/controllers/expense_types_controller.rb
class ExpenseTypesController < ApplicationController
  def new
    @expense_type = ExpenseType.new
  end

  def create
    expense_type_params = params.require(:expense_type).permit(:description,
                                                            :accounting_account)

    @expense_type = ExpenseType.create(expense_type_params)

    if @expense_type.save
      redirect_to @expense_type
    else
      flash[:error] = 'Não foi possível cadastrar.'
      render :new
    end
  end

  def show
    @expense_type = ExpenseType.find(params[:id])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense_report = ExpenseReport.find(params[:expense_report_id])
    @expense =  Expense.new
    @expense_subtypes = ExpenseSubtype.all
    @customers = Customer.all
  end

  def create
    @expense_subtypes = ExpenseSubtype.all
    @expense_report = ExpenseReport.find(params[:expense_report_id])
    @expense = @expense_report.expenses.create(expense_params)
    @customers = Customer.all

    if @expense.save
      redirect_to @expense_report
    else
      flash[:error] = 'Não foi possível criar esta despesa'
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:expense_subtype_id, :value, :customer_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.approver?
      @expense_reports = ExpenseReport.submitted
    elsif current_user.salesman?
      @expense_reports = current_user.expense_reports.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.erb
<h3>Clientes Ativos</h3>
<%= link_to 'Cadastrar um cliente', new_customer_path %> <br/>

<h3>Clientes Pendentes</h3>
<%= @pending_customers.each do |customer| %>
  <%= link_to customer.name, customer_path(customer) %>
<% end %>

app/views/customers/new.html.erb
<h2>Cadastrar um cliente</h2>

<%= form_for(@customer) do |f| %>
  <div>
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :social_name, 'Razão Social' %>
    <%= f.text_field :social_name %>
  </div>
  <div>
    <%= f.label :cnpj, 'CNPJ' %>
    <%= f.text_field :cnpj %>
  </div>
  <%= f.submit 'Cadastrar' %>
<% end %>

app/views/customers/show.html.erb
<h3><%= @customer.name %></h3>

<p>Razão Social: <%= @customer.social_name %></p>
<p>CNPJ: <%= @customer.cnpj %></p>
<p>Cadastrado por: <%= @customer.user.email %> </p>

<p>Status: <%= @customer.status %>

<%= link_to 'Aprovar', customer_approve_path(@customer), method: :post %>

app/views/expense_reports/new.html.erb
<h2>Cadastrar um relatório</h2>

<%= form_for(@expense_report) do |f|%>
  <div>
    <%= f.label :title, 'Descrição'%>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :start_date, 'Data inicial'%>
    <%= f.date_field :start_date%>
     |
    <%= f.label :end_date, 'Data final'%>
    <%= f.date_field :end_date%>
  </div>
  <div>
    <%= f.label 'Carro próprio?'%>
    <%= f.radio_button :own_car, true %>
    <%= label :own_car, 'Sim'%>
    <%= f.radio_button :own_car, false %>
    <%= label :own_car, 'Não'%>
  </div>
  <%= f.submit 'Cadastrar' %>
<% end %>

app/views/expense_reports/show.html.erb
<h3><%= @expense_report.title %></h3>

<h4>Despesas</h4>
<%= link_to 'Cadastrar uma despesa', new_expense_report_expense_path(@expense_report) %>
<br/><br/>
<% @expense_report.expenses.each do |expense| %>
  <h6><%= expense.expense_subtype.description %></h6>
  <ul>
    <% if expense.customer_id? %>
      <li>Cliente: <%= expense.customer.name %> </li>
    <% end %>
    <li>Valor: R$ <%= expense.value %> </li>
    <br />
  </ul>
<% end %>

<h4>Comentários</h4>
<% if @expense_report.comments.any? %>
  <% @expense_report.comments.each do |comment| %>
    <b><%= comment.user.email %></b> <br />
    <p><%= comment.message %></p>
    <hr>
  <% end %>
<% else %>
  <p> Ainda não existem comentários.</p>
<% end %>
<% if current_user.approver? %>
  <%= form_for([@expense_report,@comment]) do |f| %>
    <div>
      <%= f.label :message, 'Adicionar comentário'%> <br/>
      <%= f.text_area :message %> <br />
    </div>
    <%= f.submit 'Enviar comentário' %>
  <% end %>
  <%= link_to 'Aprovar', expense_report_approve_path(@expense_report) %>
<% else %>
  <% if @expense_report.status == 'saved' %>
    <%= link_to 'Submeter à aprovação', expense_report_submit_path(@expense_report), method: :post %>
  <% elsif @expense_report.status == 'submitted' %>
    <p>Status: Aguardando aprovação</p>
  <% else %>
    <p>Status: <%= @expense_report.status %></p>

    <%= form_for([@expense_report,@comment]) do |f| %>
      <div>
        <%= f.label :message, 'Adicionar comentário'%> <br/>
        <%= f.text_area :message %> <br />
      </div>
      <%= f.submit 'Enviar comentário' %>
    <% end %>

  <% end %>
<% end %>
<br />
<%= link_to 'Voltar', root_path %>

app/views/expense_subtypes/new.html.erb
<h3>Cadastrar Subtipo de Despesa</h3>

<%= form_for(@expense_subtype) do |f| %>
  <div>
    <%= f.label :expense_type_id, 'Tipo' %>
    <%= f.collection_select(:expense_type_id, ExpenseType.all, :id, :description) %>
  </div>
  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :accounting_account, 'Conta Contábil' %>
    <%= f.text_field :accounting_account %>
  </div>
    <div>
    <%= f.label :needs_customer, 'Precisa de um cliente?' %>
    <%= f.select(:needs_customer,options_for_select([['Sim', true], ['Não', false]],false)) %>
  </div>
  <%= f.submit 'Cadastrar' %>
<% end %>

app/views/expense_subtypes/show.html.erb
<h5><%= @expense_subtype.description %></h5>

<p>Conta Contábil: <%= @expense_subtype.accounting_account %></p>
<p>Tipo: <%= @expense_subtype.expense_type.description %></p>
<p>Precisa de um cliente? <%= @expense_subtype.needs_customer ? 'Sim' : 'Não' %> </p>

app/views/expense_types/new.html.erb
<h3>Cadastrar Tipo de Despesa</h3>

<%= form_for(@expense_type) do |f| %>
  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit 'Cadastrar' %>
<% end %>

app/views/expense_types/show.html.erb
<h5><%= @expense_type.description %></h5>
<ul>
</ul>

app/views/expenses/new.html.erb
<h2>Cadastrar uma despesa</h2>

<%= form_for([@expense_report, @expense]) do |f| %>
  <div>
    <%= f.label :expense_subtype_id, 'Classificação' %>
    <%= f.collection_select(:expense_subtype_id, @expense_subtypes, :id, :description) %>
  </div>
  <div>
    <%= f.label :customer_id, 'Cliente' %>
    <%= f.collection_select(:customer_id, @customers, :id, :name) %>
  </div>
  <div>
    <%= f.label :value, 'Valor' %>
    <%= f.text_field :value %>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/home/index.html.erb
<h1>Bem-vindo ao Controle de Despesas</h1>

<h3>Relatórios de Despesas</h3>
<div>
  <%= link_to 'Cadastrar um relatório de despesas', new_expense_report_path %> <br/>
  <%= link_to 'Cadastrar Tipo de Despesa', new_expense_type_path %> <br/>
  <%= link_to 'Cadastrar Subtipo de Despesa', new_expense_subtype_path %> <br/>
  <%= link_to 'Clientes', customers_path %>
</div>
<% if @expense_reports.nil? %>
  <p>Não existem Relatórios de Despesas</p>
<% else %>
  <% @expense_reports.each do |report| %>
    <br />
    <%= link_to report.title, expense_report_path(report) %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controle de Despesas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="error"><%= flash[:error] %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%= link_to 'Home', root_path %>
<% if user_signed_in? %>
  | <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% else %>
  | <%= link_to 'Entrar', new_user_session_path %>
<% end %>